name: Keep Streamlit Awake

on:
  schedule:
    - cron: "0 */6 * * *" # Runs automatically every 6 hours to reset the 12h clock
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Reset Streamlit Timer
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit --allow-empty -m "Keeping the room booking app awake"
          git push
